# Generated by Django 5.2.5 on 2026-06-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_hotel", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="type_ar",
            new_name="event_type_ar",
        ),
        migrations.RenameField(
            model_name="booking",
            old_name="type_en",
            new_name="event_type_en",
        ),
        migrations.AddField(
            model_name="booking",
            name="time_slot",
            field=models.CharField(
                choices=[
                    ("morning", "Morning Shift"),
                    ("afternoon", "Afternoon Shift"),
                    ("night", "Night Shift"),
                ],
                default="morning",
                help_text="Event time slot: Morning Shift, Afternoon Shift, or Night Shift",
                max_length=20,
            ),
        ),
    ]
