# Generated by Django 5.2.5 on 2026-07-26 19:25

import apps.my_hotel.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_hotel", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "time_slot",
                    models.CharField(
                        choices=[
                            ("morning", "Morning Shift"),
                            ("afternoon", "Afternoon Shift"),
                            ("night", "Night Shift"),
                        ],
                        help_text="Time slot: Morning Shift, Afternoon Shift, or Night Shift",
                        max_length=20,
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("valid_from", models.DateField()),
                (
                    "valid_until",
                    models.DateField(
                        blank=True, help_text="Leave blank for no end date", null=True
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="bookingservice",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="my_hotel.booking",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="my_hotel.booking",
            ),
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "name_en",
                    models.CharField(
                        max_length=150,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_name",
                                message="Name can only contain alphabets and spaces.",
                                regex="^[A-Za-z\\s]+$",
                            )
                        ],
                    ),
                ),
                ("name_ar", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "code_name",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_code_name",
                                message="Code name can only contain alphabets and underscores (_).",
                                regex="^[A-Za-z_]+$",
                            )
                        ],
                    ),
                ),
                (
                    "capacity",
                    models.CharField(
                        help_text='Display string, e.g. "50 Guests"', max_length=50
                    ),
                ),
                ("capacity_count", models.PositiveIntegerField(blank=True, null=True)),
                ("badge", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to=apps.my_hotel.models.get_room_image_path,
                    ),
                ),
                ("occupied", models.BooleanField(default=False)),
                (
                    "occupied_dates",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("booking_count", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="my_hotel.hall",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RoomAmenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "name_en",
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_name",
                                message="Name can only contain alphabets and spaces.",
                                regex="^[A-Za-z\\s]+$",
                            )
                        ],
                    ),
                ),
                ("name_ar", models.CharField(blank=True, max_length=100, null=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("description_ar", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amenities",
                        to="my_hotel.room",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RoomBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "booking_code",
                    models.CharField(
                        blank=True,
                        help_text='Human-readable ID like "RB1001" (auto-generated if blank)',
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "event_type_en",
                    models.CharField(
                        help_text='Event type, e.g. "Meeting"', max_length=100
                    ),
                ),
                (
                    "event_type_ar",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date", models.DateField()),
                (
                    "time_slot",
                    models.CharField(
                        choices=[
                            ("morning", "Morning Shift"),
                            ("afternoon", "Afternoon Shift"),
                            ("night", "Night Shift"),
                        ],
                        default="morning",
                        help_text="Room time slot: Morning Shift, Afternoon Shift, or Night Shift",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "confirmed"),
                            ("pending", "pending"),
                            ("cancelled", "cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="room_bookings",
                        to="my_hotel.booking",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_bookings",
                        to="my_hotel.customer",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="my_hotel.room",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="bookingservice",
            name="room_booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="my_hotel.roombooking",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="room_booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="my_hotel.roombooking",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookingservice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("booking__isnull", False), ("room_booking__isnull", True)
                    ),
                    models.Q(
                        ("booking__isnull", True), ("room_booking__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="bookingservice_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("booking__isnull", False), ("room_booking__isnull", True)
                    ),
                    models.Q(
                        ("booking__isnull", True), ("room_booking__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="payment_exactly_one_target",
            ),
        ),
        migrations.AddField(
            model_name="roompricing",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="roompricing",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pricing",
                to="my_hotel.room",
            ),
        ),
        migrations.AddField(
            model_name="roompricing",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="roompricing",
            unique_together={("room", "time_slot", "valid_from")},
        ),
    ]
