# Generated by Django 5.2.5 on 2026-07-31 18:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("my_hotel", "0002_roompricing_alter_bookingservice_booking_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="hall",
        ),
    ]
